version: 2
jobs:
  test_corepops:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Test corepops
          command: |
            python3 -m pip install docker
            mkdir /tmp/artifacts
            python generate_corepop_compat_report.py > /tmp/artifacts/report.md
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  mainflow:
    jobs:
      - test_corepops
